Repository yourssu/Soomsil-USaint-iOS, pull requests merged in 2025-03, with the labels that each got.

#89 [#84] SettingView 내 ListView 분리 및 추가 리팩터링
  Soomsil-USaint/Application/AppReducer.swift
  Soomsil-USaint/Application/Feature/Setting/Core/SettingReducer.swift
  Soomsil-USaint/Application/Feature/Setting/View/ListRowView.swift
  Soomsil-USaint/Application/Feature/Setting/View/SettingView.swift
Labels: refactor🪄

#94 [#93] 최소지원버전 16.6 -> 17.0+ 로 변경
  Soomsil-USaint.xcodeproj/project.pbxproj
Labels: chore 🧹

#95 [Refactor] SemesterDetailView 리팩토링 / SemesterDetailReducer 구현
  Soomsil-USaint/Application/Feature/Home/Core/HomeReducer.swift
  Soomsil-USaint/Application/Feature/Home/View/HomeView.swift
  Soomsil-USaint/Application/Feature/Semester/Common/GradeRow.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/Core/SemesterDetailReducer.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/View/GradeRowView.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/View/RectKey.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/View/SemesterDetailView.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/View/SemesterTab.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/View/v2GradeOverView.swift
  Soomsil-USaint/Application/Feature/Semester/SemesterDetail/View/v2SemesterDetailView.swift
  Soomsil-USaint/Data/Model/GradeSummary.swift
  Soomsil-USaint/Global/Utils/CGFloat+.swift
Labels: refactor🪄

#104 [#103] HomeView 수정
  Soomsil-USaint/Application/Feature/Home/View/GradeInfo.swift
  Soomsil-USaint/Application/Feature/Home/View/HomeView.swift
Labels: feat 💜

#105 [#99] 현재가 몇년도 몇학기인지 반환하는 func 추가
  Soomsil-USaint/Data/Client/RuSaint/GradeClient.swift
Labels: refactor🪄
